name: assessment_itunes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  dio: ^5.5.0
  connectivity_plus: ^6.0.4
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  envied: ^0.5.4
  crypto: ^3.0.1
  flutter_jailbreak_detection: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_gen_runner: ^5.4.0
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  envied_generator: ^0.5.4+1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/logos/

flutter_gen:
  output: lib\src\core\assets\
